# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "puppetlabs/centos-6.5-64-puppet"
  config.vm.box_url = "http://developer.nrel.gov/downloads/vagrant-boxes/CentOS-6.4-x86_64-v20130731.box"
  
  config.vm.define :host_one do |host_one| 
    host_one.vm.hostname = "one.node"
    host_one.vm.network :private_network, ip: "192.168.0.100"
    host_one.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", 2048]
    end

    host_one.vm.network "forwarded_port", guest: 8080, host: 8080

    host_one.vm.provision "puppet" do |puppet|
      puppet.manifests_path = "manifest"
      puppet.module_path = "../modules"
      puppet.manifest_file = "host_one.pp"
    end
  end

  config.vm.define :host_two do |host_two| 
    host_two.vm.hostname = "two.node"
    host_two.vm.network :private_network, ip: "192.168.0.102"
    host_two.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", 2048]
    end

    host_two.vm.provision "puppet" do |puppet|
      puppet.manifests_path = "manifest"
      puppet.module_path = "../modules"
      puppet.manifest_file = "host_two.pp"
    end
  end
  
  config.vm.define :host_three do |host_three| 
    host_three.vm.hostname = "three.node"
    host_three.vm.network :private_network, ip: "192.168.0.103"
    host_three.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", 2048]
    end
    
    host_three.vm.provision "puppet" do |puppet|
      puppet.manifests_path = "manifest"
      puppet.module_path = "../modules"
      puppet.manifest_file = "host_three.pp"
    end
  end
end
