# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

MANIFESTS_PATH='manifest'
MODULES_PATH='../../puppet/modules'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "puppetlabs/centos-6.5-64-puppet"
  config.vm.box_url = "http://developer.nrel.gov/downloads/vagrant-boxes/CentOS-6.4-x86_64-v20130731.box"
  
  config.vm.define :host_one do |host_one| 
    host_one.vm.hostname = "one.node"
    host_one.vm.network :private_network, ip: "192.168.0.100"
    host_one.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", 2048]
    end

    host_one.vm.network "forwarded_port", guest: 8080, host: 8080

    host_one.vm.provision "puppet" do |puppet|
      puppet.manifests_path = MANIFESTS_PATH
      puppet.module_path = MODULES_PATH
      puppet.manifest_file = "host_one.pp"
    end
  end
end
