# -*- mode: ruby -*-
# # vi: set ft=ruby :
BOX="puppetlabs/centos-6.5-64-puppet"
BOX_URL="http://developer.nrel.gov/downloads/vagrant-boxes/CentOS-6.4-x86_64-v20130731.box"

HDP_AMBARI_REPO="http://public-repo-1.hortonworks.com/ambari/centos6/1.x/updates/1.7.0/ambari.repo"

nodes = [
    {:name => :one, :cpu => 1, :mem => 4096, :ip => "192.168.33.101"},
]

VAGRANTFILE_API_VERSION = "2"

PLAYBOOK_PATH='../../ansible'
PLAYBOOK_NAME='hdp_centos6_playbook.yml'

HOST_TLD = "hdp"
AMBARI_HOST_NAME = "one.%s" % HOST_TLD

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = BOX
  config.vm.box_url = BOX_URL
  
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end
  
  nodes.each do |opts|
    config.vm.define opts[:name] do |config| 
        config.vm.hostname = "%s.%s" % [opts[:name].to_s, HOST_TLD]
        config.vm.network :private_network, ip: opts[:ip]
        config.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--cpus", opts[:cpu] ] if opts[:cpu]
            vb.customize ["modifyvm", :id, "--memory", opts[:mem] || 2048 ]
        end

        config.vm.provision :hosts do |provisioner|
            provisioner.autoconfigure = false
            provisioner.add_localhost_hostnames = false
            nodes.each do |n|
                provisioner.add_host n[:ip], [ "%s.%s" % [ n[:name].to_s, HOST_TLD ], n[:name].to_s ]
            end
        end

        config.vm.network "forwarded_port", guest: 8080, host: 8080, auto_correct: true if "%s.%s" % [ opts[:name].to_s, HOST_TLD ] == AMBARI_HOST_NAME

        config.vm.provision "ansible" do |ansible|
           ansible.groups = {
               "ambari_host" => ['one']
           }
           ansible.extra_vars = {
               "hdp_ambari_repo" => HDP_AMBARI_REPO,
               "ownhostname" => "%s.%s" % [opts[:name].to_s, HOST_TLD],
               "ambarihostname" => AMBARI_HOST_NAME 
           }
           ansible.playbook = "%s/%s" % [PLAYBOOK_PATH, PLAYBOOK_NAME]
        end
    end
  end
end
